const GOOGLE_TIMEZONE_BROWSER_KEY = 'AIzaSyAs-o9mhtpo6N2D2zcsTh0ZStajK8Ihbes';
const GOOGLE_TIMEZONE_SERVER_KEY = 'AIzaSyD_o6oRAGYDSfrVUoIIgMbfFIRn-rfUkiM';
const OPENWEATHER_KEY = 'bfb3f70a8cf06a906ea097f79fba35e3';
export {GOOGLE_TIMEZONE_BROWSER_KEY, GOOGLE_TIMEZONE_SERVER_KEY, OPENWEATHER_KEY};
